[package]
name = "armin-knx"
version = "0.1.0"
authors = ["Armin <armin@arbu.eu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.20", features = ["full" ] }
reqwest = "0.11.2"
tokio = { version = "1", features = ["full"] }
regex = "1.6.0"
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
handlebars = "4.3.4"