[package]
name = "armin-knx"
version = "0.1.0"
authors = ["Armin <armin@arbu.eu>"]
edition = "2021"


[dependencies]
tauri = "1.2.1"
chrono = "0.4.22"
hyper = { version = "0.14", features = ["full" ] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"
regex = "1.6.0"
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
handlebars = "4.3.4"