[package]
name = "arbu-eb-rust"
version = "0.1.0"
authors = ["Armin Burchardt (Elektrobit) <armin.burchardt@elektrobit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
