[package]
name = "armin-knx"
version = "0.1.0"
authors = ["Armin <armin@arbu.eu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13.8"
tokio = { version = "0.2", features = ["full"] }
regex = "1.6.0"
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
handlebars = "4.3.4"