[package]
name = "arbu-eb-rust"
version = "0.1.0"
authors = ["Armin Burchardt (Elektrobit) <armin.burchardt@elektrobit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# http = "0.2.1"
hyper = "0.13.8"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0.57"
tokio = { version = "0.2", features = ["full"] }
handlebars = "1.1.0"
# for ffi
libc = "0.2.0"
